require:
AllCops:
  TargetRubyVersion: 3.3.2
  NewCops: enable
  Exclude:
      - db/**/*
      - config/**/*
# ===================== Metrics ====================
Style/Documentation:
  Enabled: true
  Exclude:
    - app/models/application_record.rb
    - test/test_helper.rb
# ===================== Style ====================
Style/Documentation:
  Enabled: true
  Exclude:
    - db/**/*
    - app/models/application_record.rb
